# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import prodekoorg.app_poytakirjat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumentti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdrive_id', models.CharField(max_length=99)),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('doc_file', models.FileField(upload_to=prodekoorg.app_poytakirjat.models.content_directory)),
            ],
            options={
                'verbose_name': 'minutes',
                'verbose_name_plural': 'Minutes',
                'ordering': ['-date', '-number'],
            },
        ),
    ]
