# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_poytakirjat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumentti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('doc_file', models.FileField(upload_to='dokumentit')),
            ],
            options={
                'verbose_name': 'Dokumentti',
                'verbose_name_plural': 'Dokumentit',
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
