# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import prodekoorg.app_poytakirjat.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_poytakirjat', '0002_auto_20180419_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumentti',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dokumentti',
            name='doc_file',
            field=models.FileField(upload_to=prodekoorg.app_poytakirjat.models.content_directory),
        ),
    ]
