# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_poytakirjat', '0004_auto_20180419_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumentti',
            options={'ordering': ['date', 'number'], 'verbose_name': 'pöytäkirja', 'verbose_name_plural': 'Pöytäkirjat'},
        ),
    ]
