# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_poytakirjat', '0007_dokumentti_gdrive_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokumentti',
            options={'ordering': ['-date', '-number'], 'verbose_name': 'minutes', 'verbose_name_plural': 'Minutes'},
        ),
    ]
