# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiedotteet', '0004_auto_20180323_1815'),
        ('tiedotteet', '0004_auto_20180329_1404'),
    ]

    operations = [
    ]
