# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiedotteet', '0004_auto_20180607_1738'),
        ('tiedotteet', '0003_auto_20180606_1639'),
    ]

    operations = [
    ]
