# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiedotteet', '0022_auto_20180529_1919'),
        ('tiedotteet', '0016_auto_20180528_1646'),
    ]

    operations = [
    ]
