# Generated by Django 2.2.10 on 2020-04-12 22:12

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import prodekoorg.app_proleko.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('authors', models.CharField(max_length=255, null=True, verbose_name='Author')),
                ('ingress', models.TextField(blank=True, verbose_name='Lead')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('thumbnail', models.ImageField(blank=True, upload_to=prodekoorg.app_proleko.models.Post.form_upload_path)),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Liked by')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Lehti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020, verbose_name='Year')),
                ('issue', models.IntegerField(default=1, verbose_name='Issue')),
                ('file', models.FileField(unique=True, upload_to=prodekoorg.app_proleko.models.Lehti.form_upload_path, verbose_name='File')),
                ('thumbnail', models.ImageField(blank=True, upload_to=prodekoorg.app_proleko.models.Lehti.form_upload_path, verbose_name='Thumbnail')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'proleko',
                'verbose_name_plural': "Proleko's",
                'unique_together': {('year', 'issue')},
            },
        ),
    ]