# Generated by Django 2.2.10 on 2020-04-03 13:40

from django.db import migrations, models
import prodekoorg.app_proleko.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lehti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2020, unique=True)),
                ('issue', models.IntegerField(default=1)),
                ('file', models.FileField(unique=True, upload_to=prodekoorg.app_proleko.models.Lehti.form_upload_path)),
                ('thumbnail', models.ImageField(unique=True, upload_to=prodekoorg.app_proleko.models.Lehti.form_upload_path)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Prolekos',
            },
        ),
    ]
