# Generated by Django 2.2.10 on 2020-04-27 09:26

from django.db import migrations, models
import prodekoorg.app_proleko.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proleko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Company name')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to=prodekoorg.app_proleko.models.Ad.form_upload_path, verbose_name='Image')),
            ],
        ),
    ]