# Generated by Django 2.2.10 on 2020-04-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proleko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lehti',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterUniqueTogether(
            name='lehti',
            unique_together={('year', 'issue')},
        ),
    ]
