# Generated by Django 3.1.4 on 2021-01-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proleko', '0002_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lehti',
            name='year',
            field=models.IntegerField(default=2021, verbose_name='Year'),
        ),
    ]
