# Generated by Django 2.2.10 on 2020-04-08 20:23

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_proleko', '0003_auto_20200408_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sisältö'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingress',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Ingressi'),
        ),
    ]
