# Generated by Django 3.1.4 on 2023-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proleko', '0003_auto_20210121_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lehti',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='Year'),
        ),
    ]
