# Generated by Django 2.2.10 on 2020-04-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proleko', '0004_auto_20200408_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingress',
            field=models.TextField(blank=True, verbose_name='Ingressi'),
        ),
    ]
