# Generated by Django 3.1.4 on 2025-01-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proleko', '0005_auto_20240103_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lehti',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Year'),
        ),
    ]
