# Generated by Django 2.1.10 on 2019-09-07 15:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('coaches', models.CharField(blank=True, default='', max_length=255, verbose_name='coaches')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='description')),
                ('registration', models.URLField(max_length=255, verbose_name='registration url')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='lifelonglearning', verbose_name='banner image')),
                ('groupsize', models.IntegerField(blank=True, null=True, verbose_name='group size')),
                ('timing', models.CharField(blank=True, max_length=255, null=True, verbose_name='timing')),
                ('open', models.BooleanField(verbose_name='open')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
