# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 08:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('coaches', models.CharField(blank=True, default='', max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('registration', models.URLField(max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('groupsize', models.IntegerField(blank=True, null=True)),
                ('timing', models.CharField(blank=True, max_length=255, null=True)),
                ('open', models.BooleanField()),
            ],
            options={
                'verbose_name': 'courses',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
