# Generated by Django 2.1 on 2019-07-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifelonglearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'Courses'},
        ),
    ]
