# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lifelonglearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='groupsize',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
