# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ehdokas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nimi')),
                ('pic', models.ImageField(upload_to='')),
                ('auth_prodeko_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'virka',
                'verbose_name_plural': 'Virat',
            },
        ),
        migrations.CreateModel(
            name='Kysymys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('question', models.TextField(blank=True, verbose_name='Kysymys')),
            ],
            options={
                'verbose_name': 'kysymys',
                'verbose_name_plural': 'Kysymykset',
            },
        ),
        migrations.CreateModel(
            name='Virka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hallitus', models.BooleanField(default=False, verbose_name='Hallitus')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='Jaos')),
                ('name', models.CharField(max_length=50, verbose_name='Virka')),
                ('auth_prodeko_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ehdokas',
                'verbose_name_plural': 'Ehdokkaat',
            },
        ),
        migrations.AddField(
            model_name='kysymys',
            name='to_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vaalit.Virka'),
        ),
        migrations.AddField(
            model_name='ehdokas',
            name='virka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vaalit.Virka'),
        ),
    ]
