# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 17:57
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ehdokas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('introduction', ckeditor.fields.RichTextField()),
                ('pic', models.ImageField(blank=True, upload_to='', verbose_name='Picture')),
                ('auth_prodeko_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'applicant',
                'verbose_name_plural': 'Applicants',
            },
        ),
        migrations.CreateModel(
            name='Kysymys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('question', models.TextField(verbose_name='Question')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vastaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('by_ehdokas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_by', to='app_vaalit.Ehdokas')),
                ('to_question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_vaalit.Kysymys')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Virka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hallitus', models.BooleanField(default=False, verbose_name='Board')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.AddField(
            model_name='kysymys',
            name='to_virka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_vaalit.Virka'),
        ),
        migrations.AddField(
            model_name='ehdokas',
            name='virka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehdokkaat', to='app_vaalit.Virka'),
        ),
        migrations.AlterUniqueTogether(
            name='ehdokas',
            unique_together=set([('auth_prodeko_user', 'virka')]),
        ),
    ]
