# Generated by Django 2.2.5 on 2019-10-29 13:09

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehdokas',
            name='pic',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='images/toimari_photos/placeholder.jpg', upload_to='app_vaalit/ehdokas_photos', verbose_name='Picture'),
        ),
    ]
