# Generated by Django 2.2.5 on 2019-10-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virka',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
    ]
