# Generated by Django 3.0.10 on 2020-11-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0002_pic_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='virka',
            name='sort_key',
            field=models.CharField(default='ZZZ', max_length=50, verbose_name='Sort-key'),
        ),
    ]
