# Generated by Django 2.2.5 on 2019-10-13 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_vaalit', '0002_virka_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='virka',
            name='read_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Read by'),
        ),
    ]
