# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0002_remove_virka_auth_prodeko_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ehdokas',
            options={'verbose_name': 'ehdokas', 'verbose_name_plural': 'Ehdokkaat'},
        ),
        migrations.AlterModelOptions(
            name='virka',
            options={'verbose_name': 'virka', 'verbose_name_plural': 'Virat'},
        ),
    ]
