# Generated by Django 3.1.3 on 2020-11-22 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0003_virka_sort_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kysymys',
            name='to_virka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_vaalit.virka'),
        ),
        migrations.AlterField(
            model_name='vastaus',
            name='by_ehdokas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_by', to='app_vaalit.ehdokas'),
        ),
        migrations.AlterField(
            model_name='vastaus',
            name='to_question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_vaalit.kysymys'),
        ),
    ]
