# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0004_auto_20180520_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehdokas',
            name='auth_prodeko_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ehdokas',
            name='virka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehdokkaat', to='app_vaalit.Virka'),
        ),
    ]
