# Generated by Django 3.1.4 on 2023-10-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0004_change_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='virka',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
    ]
