# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0005_auto_20180521_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kysymys',
            name='to_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kysymykset', to='app_vaalit.Virka'),
        ),
    ]
