# Generated by Django 3.1.4 on 2023-10-17 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0005_virka_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='virka',
            name='application_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Application start date'),
        ),
    ]
