# Generated by Django 3.1.4 on 2023-11-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0006_virka_application_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehdokas',
            name='be_unclickable',
            field=models.BooleanField(default=False, verbose_name=':D'),
        ),
    ]
