# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0006_auto_20180524_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehdokas',
            name='introduction',
            field=models.TextField(default='tmp', verbose_name='Esittely'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ehdokas',
            name='pic',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Kuva'),
        ),
    ]
