# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0008_auto_20180527_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehdokas',
            name='virka',
        ),
        migrations.AddField(
            model_name='ehdokas',
            name='virka',
            field=models.ManyToManyField(related_name='ehdokkaat', to='app_vaalit.Virka'),
        ),
    ]
