# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0009_auto_20180529_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kysymys',
            name='question',
            field=models.TextField(verbose_name='Kysymys'),
        ),
    ]
