# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0012_auto_20180605_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vastaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('answer', models.TextField(verbose_name='Vastaus')),
                ('by_ehdokas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vastaaja', to='app_vaalit.Ehdokas')),
                ('to_question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vastaukset', to='app_vaalit.Kysymys')),
            ],
            options={
                'verbose_name_plural': 'Vastaukset',
                'verbose_name': 'vastaus',
            },
        ),
    ]
