# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0015_kysymys_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virka',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Virka'),
        ),
    ]
