# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0016_auto_20180609_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehdokas',
            name='virka',
        ),
        migrations.AddField(
            model_name='ehdokas',
            name='virka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ehdokkaat', to='app_vaalit.Virka'),
            preserve_default=False,
        ),
    ]
