# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_vaalit', '0017_auto_20180609_1543'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ehdokas',
            unique_together=set([('auth_prodeko_user', 'virka')]),
        ),
    ]
