# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0018_auto_20180610_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virka',
            name='section',
        ),
    ]
