# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 10:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0019_remove_virka_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kysymys',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
