# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0020_auto_20180617_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kysymys',
            options={'ordering': ['-created_at'], 'verbose_name': 'kysymys', 'verbose_name_plural': 'Kysymykset'},
        ),
    ]
