# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0021_auto_20180618_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vastaus',
            options={'ordering': ['-created_at'], 'verbose_name': 'vastaus', 'verbose_name_plural': 'Vastaukset'},
        ),
    ]
