# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0022_auto_20180621_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ehdokas',
            options={'verbose_name': 'applicant', 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AlterModelOptions(
            name='kysymys',
            options={'ordering': ['-created_at'], 'verbose_name': 'question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='vastaus',
            options={'ordering': ['-created_at'], 'verbose_name': 'answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='virka',
            options={'verbose_name': 'position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterField(
            model_name='ehdokas',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ehdokas',
            name='pic',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='kysymys',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='kysymys',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='kysymys',
            name='to_virka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_vaalit.Virka'),
        ),
        migrations.AlterField(
            model_name='vastaus',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='vastaus',
            name='by_ehdokas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_by', to='app_vaalit.Ehdokas'),
        ),
        migrations.AlterField(
            model_name='vastaus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='vastaus',
            name='to_question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_vaalit.Kysymys'),
        ),
        migrations.AlterField(
            model_name='virka',
            name='is_hallitus',
            field=models.BooleanField(default=False, verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='virka',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Position'),
        ),
    ]
