# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_vaalit', '0023_auto_20180926_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kysymys',
            name='to_virka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kysymykset', to='app_vaalit.Virka'),
        ),
        migrations.AlterField(
            model_name='vastaus',
            name='by_ehdokas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vastaaja', to='app_vaalit.Ehdokas'),
        ),
        migrations.AlterField(
            model_name='vastaus',
            name='to_question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vastaukset', to='app_vaalit.Kysymys'),
        ),
    ]
