version: '3.8'

services:
  redis:
    image: redis:6-alpine
    container_name: prodeko_org_redis
    restart: unless-stopped
    volumes:
      - 'prodeko-org-redis:/data'

  prodeko_org:
    image: prodekoregistry.azurecr.io/prodeko-org/prodeko-org:latest
    container_name: prodeko_org
    restart: unless-stopped
    command: uvicorn --host prodeko_org --workers 5 --interface asgi3 --loop asyncio --lifespan off prodekoorg.asgi:application
    volumes:
      - ./prodekoorg:/app/prodekoorg
    environment:
      - DJANGO_SETTINGS_MODULE=prodekoorg.settings.prod
      - POSTGRESQL_SSL_CA=/app/ca-certs/BaltimoreCyberTrustRoot.crt.pem

volumes:
  prodeko-org-redis:
    external: true

networks:
  default:
    external:
      name: prodeko-docker-net
