version: '3.8'

services:
  redis:
    image: redis:6-alpine
    container_name: prodeko_org_redis
    restart: unless-stopped
    volumes:
      - 'prodeko-org-redis:/data'

  prodeko_org:
    image: prodekoregistry.azurecr.io/prodeko-org/prodeko-org:latest
    container_name: prodeko_org
    restart: unless-stopped
    # command: uvicorn --host prodeko_org --workers 5 --interface wsgi --lifespan off prodekoorg.wsgi:application
    # Each thread manages its own database connection
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 --threads 10 prodekoorg.wsgi:application
    volumes:
      - ./prodekoorg:/app/prodekoorg
    environment:
      - DJANGO_SETTINGS_MODULE=prodekoorg.settings.prod

volumes:
  prodeko-org-redis:
    external: true

networks:
  default:
    external:
      name: prodeko-docker-net
