# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_prodeko', '0001_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_policies',
            field=models.BooleanField(default=False, verbose_name='Has accepted policies'),
            preserve_default=False,
        ),
    ]
