# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_prodeko', '0001_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_policies',
            field=models.BooleanField(default=False, help_text="Designates whether the user has accepted Prodeko's privacy policy and cookie policy.", verbose_name='Accepted privacy and cookie policy'),
        ),
    ]
