# Generated by Django 5.2.12 on 2026-08-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_prodeko', '0002_first_name_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_linked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Keycloak linked at'),
        ),
        migrations.AddField(
            model_name='user',
            name='keycloak_sub',
            field=models.CharField(blank=True, editable=False, help_text='The subject claim of the Keycloak identity this account is linked to. Empty for accounts that have never signed in through Keycloak.', max_length=255, null=True, unique=True, verbose_name='Keycloak subject'),
        ),
    ]
