# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rekisteri', '0001_initial'),
        ('auth_prodeko', '0002_user_has_accepted_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='rekisteri.Person', verbose_name='Alumn registry profile'),
        ),
    ]
