# Generated by Django 2.1 on 2019-06-21 22:52

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import prodekoorg.app_infoscreen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(default=prodekoorg.app_infoscreen.models.get_enddate)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
