# Generated by Django 2.1 on 2019-06-22 21:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import djangocms_text_ckeditor.fields
import prodekoorg.app_infoscreen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', djangocms_text_ckeditor.fields.HTMLField()),
                ('image', models.FileField(null=True, upload_to='infoscreen', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(default=prodekoorg.app_infoscreen.models.get_enddate)),
                ('highlight', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
