# Generated by Django 2.1 on 2019-07-06 15:27

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import prodekoorg.app_infoscreen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(default=prodekoorg.app_infoscreen.models.get_enddate, verbose_name='end datetime')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='description')),
                ('image', models.FileField(null=True, upload_to='infoscreen', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='image')),
                ('highlight', models.BooleanField(default=False, verbose_name='highlight')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'Slides',
            },
        ),
    ]
