# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HallituksenJasen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='First name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Last name')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('position_eng', models.CharField(max_length=60, verbose_name='Position (English)')),
                ('mobilephone', models.CharField(max_length=20, verbose_name='Mobile phone')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'board member',
                'verbose_name_plural': 'board members',
            },
        ),
        migrations.CreateModel(
            name='Jaosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Toimari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='First name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Last name')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_toimarit.Jaosto', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'guild official',
                'verbose_name_plural': 'guild officials',
            },
        ),
        migrations.AddField(
            model_name='hallituksenjasen',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_toimarit.Jaosto', verbose_name='Section'),
        ),
    ]
