# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HallituksenJasen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etunimi', models.CharField(max_length=30)),
                ('sukunimi', models.CharField(max_length=30)),
                ('virka', models.CharField(max_length=50)),
                ('virka_eng', models.CharField(max_length=60)),
                ('puhelin', models.CharField(max_length=20)),
                ('sahkoposti', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'board members',
                'verbose_name': 'board member',
            },
        ),
        migrations.CreateModel(
            name='Jaosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'sections',
                'verbose_name': 'section',
            },
        ),
        migrations.CreateModel(
            name='Toimari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etunimi', models.CharField(max_length=30)),
                ('sukunimi', models.CharField(max_length=30)),
                ('virka', models.CharField(max_length=50)),
                ('jaosto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_toimarit.Jaosto')),
            ],
            options={
                'verbose_name_plural': 'guild officials',
                'verbose_name': 'guild official',
            },
        ),
        migrations.AddField(
            model_name='hallituksenjasen',
            name='jaosto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_toimarit.Jaosto'),
        ),
    ]
