# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toimari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etunimi', models.CharField(max_length=30)),
                ('sukunimi', models.CharField(max_length=30)),
                ('virka', models.CharField(max_length=50)),
                ('jaosto', models.CharField(max_length=100)),
                ('virka_eng', models.CharField(max_length=30)),
                ('puhelin', models.CharField(max_length=20)),
                ('sahkoposti', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'toimarit',
            },
        ),
    ]
