# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallituksenjasen',
            old_name='sahkoposti',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='hallituksenjasen',
            old_name='etunimi',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='hallituksenjasen',
            old_name='sukunimi',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='hallituksenjasen',
            old_name='puhelin',
            new_name='mobilephone',
        ),
        migrations.RenameField(
            model_name='hallituksenjasen',
            old_name='virka',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='hallituksenjasen',
            old_name='virka_eng',
            new_name='position_eng',
        ),
        migrations.RenameField(
            model_name='jaosto',
            old_name='nimi',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='toimari',
            old_name='etunimi',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='toimari',
            old_name='sukunimi',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='toimari',
            old_name='virka',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='toimari',
            old_name='jaosto',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='hallituksenjasen',
            name='jaosto',
        ),
        migrations.AddField(
            model_name='hallituksenjasen',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_toimarit.Jaosto'),
        ),
    ]
