# Generated by Django 2.2.5 on 2019-10-15 12:26

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallituksenjasen',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='images/hallitus_photos/placeholder.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='toimari',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='images/toimari_photos/placeholder.jpg', upload_to=''),
        ),
    ]
