# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0002_auto_20180422_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toimari',
            name='virka_eng',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
