# Generated by Django 2.2.5 on 2020-02-04 14:56

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0002_add_photo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='toimari',
            name='photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Photo'),
        ),
    ]
