# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0002_auto_20181226_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='email',
            field=models.CharField(max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='firstname',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='lastname',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='mobilephone',
            field=models.CharField(max_length=20, verbose_name='Mobile phone'),
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='position_eng',
            field=models.CharField(max_length=60, verbose_name='Position (English)'),
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_toimarit.Jaosto', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='jaosto',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='toimari',
            name='firstname',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='toimari',
            name='lastname',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='toimari',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='toimari',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_toimarit.Jaosto', verbose_name='Section'),
        ),
    ]
