# Generated by Django 2.2.5 on 2020-02-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0003_auto_use_filer_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallituksenjasen',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toimari',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
