# Generated by Django 2.2.9 on 2020-02-06 20:52

from django.db import migrations, models
import prodekoorg.app_toimarit.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0003_use_filer_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallituksenjasen',
            name='year',
            field=models.IntegerField(default=prodekoorg.app_toimarit.models.default_year, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='toimari',
            name='year',
            field=models.IntegerField(default=prodekoorg.app_toimarit.models.default_year, verbose_name='Year'),
        ),
    ]
