# Generated by Django 2.2.9 on 2020-02-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0004_add_year_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallituksenjasen',
            old_name='position_eng',
            new_name='position_en',
        ),
        migrations.RenameField(
            model_name='hallituksenjasen',
            old_name='position',
            new_name='position_fi',
        ),
        migrations.RemoveField(
            model_name='hallituksenjasen',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hallituksenjasen',
            name='section',
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='mobilephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile phone'),
        ),
    ]
