# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0004_hallituksenjasen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toimari',
            name='puhelin',
        ),
        migrations.RemoveField(
            model_name='toimari',
            name='sahkoposti',
        ),
        migrations.RemoveField(
            model_name='toimari',
            name='virka_eng',
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='puhelin',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='sahkoposti',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='virka_eng',
            field=models.CharField(max_length=60),
        ),
    ]
