# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0005_auto_20181226_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallituksenjasen',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='hallituksenjasen',
            name='telegram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram'),
        ),
    ]
