# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0006_jaosto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toimari',
            name='jaosto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_toimarit.Jaosto'),
        ),
    ]
