# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0007_auto_20180904_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jaosto',
            options={'verbose_name_plural': 'jaostot'},
        ),
        migrations.AlterField(
            model_name='hallituksenjasen',
            name='jaosto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_toimarit.Jaosto'),
        ),
    ]
