# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_toimarit', '0008_auto_20180904_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallituksenjasen',
            options={'verbose_name': 'board member', 'verbose_name_plural': 'board members'},
        ),
        migrations.AlterModelOptions(
            name='jaosto',
            options={'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='toimari',
            options={'verbose_name': 'guild official', 'verbose_name_plural': 'guild officials'},
        ),
    ]
