# Generated by Django 2.2.10 on 2020-02-09 20:13

import django.core.validators
from django.db import migrations, models
import prodekoorg.app_membership.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='start_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1966), prodekoorg.app_membership.models.max_value_current_year], verbose_name='Year'),
        ),
    ]
