# Generated by Django 3.1.4 on 2023-12-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membership', '0003_change_start_year_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='Has paid the membership fee'),
        ),
    ]
