# Generated by Django 3.1.4 on 2024-01-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_membership', '0005_remove_pendinguser_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment intent ID'),
        ),
    ]
