# Generated by Django 2.2.5 on 2019-10-17 20:46

from django.db import migrations, models
import tiedotteet.backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'bulletin', 'verbose_name_plural': 'Bulletins'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='message',
            name='deadline_date',
            field=models.DateField(blank=True, default=tiedotteet.backend.models.default_date, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='end_date',
            field=models.DateField(default=tiedotteet.backend.models.default_date),
        ),
    ]
