# Generated by Django 2.2.5 on 2019-10-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_fix_default_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='tiedotteet_category',
        ),
        migrations.AlterModelTable(
            name='mailconfiguration',
            table='tiedotteet_mailconfiguration',
        ),
        migrations.AlterModelTable(
            name='message',
            table='tiedotteet_message',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tiedotteet_tag',
        ),
    ]
