# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prodekoorg.app_kulukorvaus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kulukorvaus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('created_by', models.CharField(max_length=50, verbose_name='Nimi')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Sähköposti')),
                ('position_in_guild', models.CharField(choices=[('Hallitus', 'Hallitus'), ('Toimihenkilö', 'Toimihenkilö')], max_length=12, verbose_name='Asema killassa')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Puhelinnumero')),
                ('bank_number', models.CharField(max_length=32, verbose_name='Tilinumero (IBAN)')),
                ('bic', models.CharField(choices=[('OP Ryhmä', 'OKOYFIHH'), ('Nordea', 'NDEAFIHH'), ('S Pankki', 'SBANFIHH'), ('Danske Bank', 'DABAFIHH'), ('Handelsbanken', 'HANDFIHH')], max_length=11, verbose_name='BIC')),
                ('target', models.CharField(max_length=50, verbose_name='Kulun selite')),
                ('explanation', models.TextField(verbose_name='Tapahtuma / kulun kohde')),
                ('sum_euros', models.PositiveIntegerField(verbose_name='Summa (euroa)')),
                ('additional_info', models.TextField(blank=True, verbose_name='Lisätietoja, kulujen perusteita')),
                ('receipt', models.FileField(upload_to='kulukorvaukset', validators=[prodekoorg.app_kulukorvaus.models.validate_file_extension], verbose_name='Kuitti')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'kulukorvaus',
                'verbose_name_plural': 'Kulukorvaukset',
            },
        ),
    ]
