# Generated by Django 2.1.10 on 2019-09-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app_kulukorvaus", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="kulukorvausperustiedot",
            name="status",
            field=models.CharField(
                choices=[("NEW", "New"), ("IP", "In process"), ("PR", "Processed")],
                default="NEW",
                max_length=50,
                verbose_name="Status",
            ),
        )
    ]
