# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import prodekoorg.app_kulukorvaus.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kulukorvaus', '0002_auto_20180513_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulukorvaus',
            name='bic',
            field=models.CharField(choices=[('OKOYFIHH', 'OKOYFIHH'), ('NDEAFIHH', 'NDEAFIHH'), ('SBANFIHH', 'SBANFIHH'), ('DABAFIHH', 'DABAFIHH'), ('HANDFIHH', 'HANDFIHH')], max_length=11, verbose_name='BIC'),
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Sähköposti'),
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='receipt',
            field=models.FileField(upload_to='kulukorvaukset/%Y-%m', validators=[prodekoorg.app_kulukorvaus.models.validate_file_extension], verbose_name='Kuitti'),
        ),
    ]
