# Generated by Django 2.1.10 on 2019-09-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kulukorvaus', '0003_auto_20190828_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='kulukorvaus',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IP', 'In process'), ('PR', 'Processed')], default='NEW', max_length=50, verbose_name='Status'),
        ),
    ]
