# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_kulukorvaus', '0003_auto_20180513_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='KulukorvausPerustiedot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=50, verbose_name='Nimi')),
                ('email', models.EmailField(max_length=254, verbose_name='Sähköposti')),
                ('position_in_guild', models.CharField(choices=[('Hallitus', 'Hallitus'), ('Toimihenkilö', 'Toimihenkilö')], max_length=12, verbose_name='Asema killassa')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Puhelinnumero')),
                ('bank_number', models.CharField(max_length=32, verbose_name='Tilinumero (IBAN)')),
                ('bic', models.CharField(choices=[('OKOYFIHH', 'OKOYFIHH'), ('NDEAFIHH', 'NDEAFIHH'), ('SBANFIHH', 'SBANFIHH'), ('DABAFIHH', 'DABAFIHH'), ('HANDFIHH', 'HANDFIHH')], max_length=11, verbose_name='BIC')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='bank_number',
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='position_in_guild',
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
