# Generated by Django 2.2.5 on 2020-03-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kulukorvaus', '0004_modify_upload_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulukorvausperustiedot',
            name='bic',
            field=models.CharField(choices=[('Aktia', 'HELSFIHH'), ('Danske Bank', 'DABAFIHH'), ('Danske Bank', 'DABAFIHX'), ('Handelsbanken', 'HANDFIHH'), ('Nordea', 'NDEAFIHH'), ('OmaSp', 'OMASP'), ('Osuuspankki', 'OKOYFIHH'), ('POP Pankki', 'POPFFI22'), ('S-Pankki', 'SBANFIHH'), ('Säästöpankki', 'ITELFIHH'), ('Ålandsbanken', 'AABAFI22')], max_length=11, verbose_name='BIC'),
        ),
    ]
