# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kulukorvaus', '0004_auto_20180516_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='kulukorvausperustiedot',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Lisätietoja'),
        ),
        migrations.AddField(
            model_name='kulukorvausperustiedot',
            name='sum_overall',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10, verbose_name='korvaussumma yhteensä (euroa)'),
            preserve_default=False,
        ),
    ]
