# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 21:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kulukorvaus', '0005_auto_20180518_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='kulukorvausperustiedot',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='kulukorvaukset/%Y-%m', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='receipt',
            field=models.FileField(upload_to='kulukorvaukset/%Y-%m', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='PDF'),
        ),
    ]
