# Generated by Django 3.0.10 on 2020-10-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kulukorvaus', '0005_add_bics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulukorvausperustiedot',
            name='bic',
            field=models.CharField(choices=[('Aktia', 'HELSFIHH'), ('Danske Bank', 'DABAFIHH'), ('Danske Bank', 'DABAFIHX'), ('Handelsbanken', 'HANDFIHH'), ('Nordea', 'NDEAFIHH'), ('OmaSp', 'OMASP'), ('Osuuspankki', 'OKOYFIHH'), ('POP Pankki', 'POPFFI22'), ('S-Pankki', 'SBANFIHH'), ('Säästöpankki', 'ITELFIHH'), ('Ålandsbanken', 'AABAFI22')], max_length=30, verbose_name='BIC'),
        ),
    ]
