# Generated by Django 3.1.10 on 2021-05-11 15:40

import django.core.validators
from django.db import migrations, models
import prodekoorg.app_kulukorvaus.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kulukorvaus', '0006_increase_bic_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulukorvaus',
            name='receipt',
            field=models.FileField(upload_to=prodekoorg.app_kulukorvaus.models.upload_url, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), prodekoorg.app_kulukorvaus.models.file_size], verbose_name='Receipt'),
        ),
    ]
