# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 15:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_kulukorvaus', '0009_auto_20180520_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='KulukorvausKulu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('target', models.CharField(max_length=50, verbose_name='Kulun selite')),
                ('explanation', models.CharField(max_length=100, verbose_name='Tapahtuma / kulun kohde')),
                ('sum_euros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa (euroa)')),
                ('additional_info', models.TextField(blank=True, verbose_name='Lisätietoja, kulujen perusteita')),
                ('receipt', models.FileField(upload_to='kulukorvaukset/%Y-%m', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Kuitti')),
            ],
            options={
                'verbose_name': 'kulukorvaus',
                'verbose_name_plural': 'Kulukorvaukset',
            },
        ),
        migrations.RemoveField(
            model_name='kulukorvausperustiedot',
            name='created_by_user',
        ),
        migrations.AlterModelOptions(
            name='kulukorvaus',
            options={'verbose_name': 'kulukorvaus', 'verbose_name_plural': 'Kulukorvaus'},
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='info',
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='sum_euros',
        ),
        migrations.RemoveField(
            model_name='kulukorvaus',
            name='target',
        ),
        migrations.AddField(
            model_name='kulukorvaus',
            name='bank_number',
            field=models.CharField(default='FI99999999999', max_length=32, verbose_name='Tilinumero (IBAN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kulukorvaus',
            name='bic',
            field=models.CharField(choices=[('OKOYFIHH', 'OKOYFIHH'), ('NDEAFIHH', 'NDEAFIHH'), ('SBANFIHH', 'SBANFIHH'), ('DABAFIHH', 'DABAFIHH'), ('HANDFIHH', 'HANDFIHH')], default='OKOYFIHH', max_length=11, verbose_name='BIC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kulukorvaus',
            name='created_by',
            field=models.CharField(default='webbitiimi@prodeko.org', max_length=50, verbose_name='Nimi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kulukorvaus',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kulukorvaus',
            name='email',
            field=models.EmailField(default='webbitiimi@prodeko.org', max_length=254, verbose_name='Sähköposti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kulukorvaus',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='kulukorvaukset/%Y-%m', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='kulukorvaus',
            name='phone_number',
            field=models.CharField(default=999, max_length=15, verbose_name='Puhelinnumero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kulukorvaus',
            name='position_in_guild',
            field=models.CharField(choices=[('Hallitus', 'Hallitus'), ('Toimihenkilö', 'Toimihenkilö')], default='Hallitus', max_length=12, verbose_name='Asema killassa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kulukorvaus',
            name='sum_overall',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='korvaussumma yhteensä (euroa)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Lisätietoja'),
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='KulukorvausPerustiedot',
        ),
        migrations.AddField(
            model_name='kulukorvauskulu',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_kulukorvaus.Kulukorvaus'),
        ),
    ]
