# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 14:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kulukorvaus', '0012_auto_20180909_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kulukorvaus',
            options={'verbose_name': 'reimbursement', 'verbose_name_plural': 'Reimbursements'},
        ),
        migrations.AlterModelOptions(
            name='kulukorvausperustiedot',
            options={'verbose_name': 'reimbursement basic information', 'verbose_name_plural': 'Reimbursement basic information'},
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Additional info'),
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='explanation',
            field=models.CharField(max_length=100, verbose_name='Event / expense target'),
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='receipt',
            field=models.FileField(upload_to='kulukorvaukset/%Y-%m', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='sum_euros',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sum (in €)'),
        ),
        migrations.AlterField(
            model_name='kulukorvaus',
            name='target',
            field=models.CharField(max_length=50, verbose_name='Expense explanation'),
        ),
        migrations.AlterField(
            model_name='kulukorvausperustiedot',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='kulukorvausperustiedot',
            name='bank_number',
            field=models.CharField(max_length=32, verbose_name='Account number (IBAN)'),
        ),
        migrations.AlterField(
            model_name='kulukorvausperustiedot',
            name='created_by',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='kulukorvausperustiedot',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='kulukorvausperustiedot',
            name='position_in_guild',
            field=models.CharField(choices=[('Hallitus', 'Hallitus'), ('Toimihenkilö', 'Toimihenkilö')], max_length=12, verbose_name='Position in guild'),
        ),
        migrations.AlterField(
            model_name='kulukorvausperustiedot',
            name='sum_overall',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total reimbursement (in €)'),
        ),
    ]
