# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kulukorvaus', '0013_auto_20180926_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulukorvausperustiedot',
            name='bic',
            field=models.CharField(choices=[('OP', 'OKOYFIHH'), ('NORDEA', 'NDEAFIHH'), ('SPANKKI', 'SBANFIHH'), ('DANSKE', 'DABAFIHH'), ('HANDELS', 'HANDFIHH')], max_length=11, verbose_name='BIC'),
        ),
        migrations.AlterField(
            model_name='kulukorvausperustiedot',
            name='position_in_guild',
            field=models.CharField(choices=[('H', 'Hallitus'), ('T', 'Toimihenkilö')], max_length=12, verbose_name='Position in guild'),
        ),
    ]
