# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-12 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kulukorvaus', '0014_auto_20180929_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulukorvausperustiedot',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
