# Generated by Django 2.1.10 on 2019-08-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_emails', models.CharField(choices=[('YA', 'hallitus@prodeko.org'), ('AL', 'puheenjohtaja@prodeko.org'), ('YH', 'ulkoministeri@prodeko.org'), ('AB', 'abivastaava@prodeko.org'), ('FK', 'fuksikapteeni@prodeko.org'), ('MA', 'maisterikvkapteeni@prodeko.org'), ('ME', 'mediakeisari@prodeko.org'), ('TI', 'cto@prodeko.org'), ('OP', 'opintovastaava@prodeko.org'), ('YR', 'yrityssuhdevastaava@prodeko.org'), ('EX', 'excumestari@prodeko.org'), ('TA', 'sisakumi@prodeko.org'), ('LA', 'rahastonhoitaja@prodeko.org'), ('ES', 'ulkoministeri@prodeko.org'), ('IS', 'isovastaava@prodeko.org')], max_length=150, verbose_name='Who do you wish to contact?')),
                ('message', models.TextField(verbose_name='Your message')),
                ('has_accepted_policies', models.BooleanField(blank=True, default=False, verbose_name='I accept that my email address is stored in order to be contacted regarding my message.')),
            ],
            options={
                'verbose_name': 'contact form application',
                'verbose_name_plural': 'Contact form',
            },
        ),
    ]
