# Generated by Django 2.2.5 on 2019-10-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact_emails',
            field=models.CharField(choices=[('YA', 'hallitus@prodeko.org'), ('PT', 'hallitus@prodeko.org'), ('AL', 'puheenjohtaja@prodeko.org'), ('YH', 'ulkoministeri@prodeko.org'), ('AB', 'abivastaava@prodeko.org'), ('FK', 'fuksikapteeni@prodeko.org'), ('MA', 'maisterikvkapteeni@prodeko.org'), ('ME', 'mediakeisari@prodeko.org'), ('TI', 'cto@prodeko.org'), ('OP', 'opintovastaava@prodeko.org'), ('YR', 'yrityssuhdevastaava@prodeko.org'), ('EX', 'excumestari@prodeko.org'), ('TA', 'sisakumi@prodeko.org'), ('LA', 'rahastonhoitaja@prodeko.org'), ('ES', 'ulkoministeri@prodeko.org'), ('IS', 'isovastaava@prodeko.org')], max_length=150, verbose_name='Who do you wish to contact?'),
        ),
    ]
