# Generated by Django 3.1.4 on 2023-11-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekisteri', '0002_workexperience_is_founding_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pora_member',
            field=models.BooleanField(default=True),
        ),
    ]
