# Generated by Django 2.2.5 on 2020-03-10 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tapahtuma',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('t_what', models.CharField(blank=True, max_length=140)),
                ('t_where', models.CharField(blank=True, max_length=140)),
                ('t_when', models.CharField(blank=True, max_length=140)),
                ('t_why', models.CharField(blank=True, max_length=140)),
                ('t_cost', models.CharField(blank=True, max_length=140)),
                ('t_dc', models.CharField(blank=True, max_length=140)),
                ('t_for_who', models.CharField(blank=True, max_length=140)),
                ('state', models.CharField(choices=[('S', 'Speculation'), ('D', 'Save the date'), ('P', 'Published')], default='S', max_length=1)),
                ('short_desc', models.TextField(blank=True, max_length=140, null=True)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TapahtumaLuokat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
