# Generated by Django 2.2.5 on 2020-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tapahtumat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tapahtuma',
            name='doc_file',
        ),
        migrations.RemoveField(
            model_name='tapahtuma',
            name='gdrive_id',
        ),
        migrations.RemoveField(
            model_name='tapahtuma',
            name='number',
        ),
        migrations.AddField(
            model_name='tapahtuma',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
