# Generated by Django 2.2.5 on 2020-01-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tapahtumat', '0002_auto_20200111_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapahtuma',
            name='short_desc',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='tapahtuma',
            name='state',
            field=models.CharField(choices=[('S', 'Speculation'), ('D', 'Save the date'), ('P', 'Published')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='tapahtuma',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
