# Generated by Django 2.2.5 on 2020-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tapahtumat', '0003_auto_20200111_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapahtuma',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tapahtuma',
            name='short_desc',
            field=models.TextField(blank=True, max_length=140, null=True),
        ),
    ]
