# Generated by Django 2.2.5 on 2020-01-13 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tapahtumat', '0004_auto_20200113_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tapahtuma',
            options={'ordering': ['-date'], 'verbose_name': 'event', 'verbose_name_plural': 'Events'},
        ),
    ]
