# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiedosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, unique=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='file_thumbnail_images')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='TiedostoVersio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('file', models.FileField(unique=True, upload_to='files')),
                ('tiedosto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app_tiedostot.Tiedosto')),
            ],
            options={
                'verbose_name': 'file version',
                'verbose_name_plural': 'File versions',
            },
        ),
    ]
