# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 10:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nimi')),
                ('hometown', models.CharField(max_length=50, verbose_name='Kotipaikka')),
                ('field_of_study', models.CharField(max_length=50, verbose_name='Opiskeluala')),
                ('email', models.EmailField(max_length=254, verbose_name='Sähköposti')),
                ('start_year', models.IntegerField(choices=[(1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2018, verbose_name='year')),
                ('membership_type', models.CharField(choices=[('Varsinainen Jäsen', 'Hallitus'), ('Alumni', 'Alumni'), ('Ulkojäsen', 'Ulkojäsen')], max_length=12, verbose_name='Jäsentyyppi')),
                ('additional_info', models.TextField(blank=True, verbose_name='Miksi haluat jäseneksi?')),
                ('is_ayy_member', models.CharField(choices=[('Kyllä', 'Kyllä'), ('Ei', 'Ei')], max_length=12, verbose_name='Oletko AYY:n jäsen?')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='jäsenhakemukset/%Y-%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Kuitti jäsenmaksusta')),
            ],
            options={
                'verbose_name_plural': 'Jäsenhakemukset',
                'verbose_name': 'jäsenhakemus',
            },
        ),
    ]
