# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 00:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('hometown', models.CharField(max_length=50, verbose_name='Hometown')),
                ('field_of_study', models.CharField(max_length=50, verbose_name='Field of study')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('start_year', models.IntegerField(choices=[(2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966)], default=2018, verbose_name='Year')),
                ('membership_type', models.CharField(choices=[('TR', 'True member'), ('AL', 'Alumn'), ('EX', 'External member')], max_length=2, verbose_name='Membership type')),
                ('additional_info', models.TextField(blank=True, verbose_name='Why do you want to become a member?')),
                ('is_ayy_member', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Are you an AYY (Aalto University Student Union) member?')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='jasenhakemukset/%Y-%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Receipt of the membership payment')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membership application',
                'verbose_name_plural': 'Membership applications',
            },
        ),
    ]
