# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apply_for_membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='language',
            field=models.CharField(choices=[('FI', 'Finnish'), ('EN', 'Other (English)')], default='FI', max_length=50, verbose_name='Nationality (language)'),
            preserve_default=False,
        ),
    ]
