# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 12:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apply_for_membership', '0002_auto_20180925_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendinguser',
            options={'verbose_name': 'membership application', 'verbose_name_plural': 'Membership applications'},
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Why do you want to become a member?'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='field_of_study',
            field=models.CharField(max_length=50, verbose_name='Field of study'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='hometown',
            field=models.CharField(max_length=50, verbose_name='Hometown'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='is_ayy_member',
            field=models.CharField(choices=[('Kyllä', 'Yes'), ('Ei', 'No')], max_length=12, verbose_name='Are you an AYY (Aalto University Student Union) member?'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='membership_type',
            field=models.CharField(choices=[('1', 'True member'), ('2', 'Alumn'), ('3', 'External member')], max_length=50, verbose_name='Membership type'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='jäsenhakemukset/%Y-%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Receipt of the membership payment'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='start_year',
            field=models.IntegerField(choices=[(2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966)], default=2018, verbose_name='Year'),
        ),
    ]
