# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 19:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apply_for_membership', '0004_pendinguser_has_accepted_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='receipt',
            field=models.FileField(upload_to='jasenhakemukset/%Y-%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Receipt of the membership payment'),
        ),
    ]
